---
# handlers file for ansible-role-proxmox-lxc
# handlers file for lxc-template
- name: Restart ssh
  service:
    name: sshd
    state: restarted
  delegate_to: "{{ lxc_hostname }}"

- name: Remove the temporary Docker installation script
  ansible.builtin.file:
    path: /tmp/get-docker.sh
    state: absent
  when: not docker_check_result.results | map(attribute='stat.exists') | bool
  delegate_to: "{{ lxc_hostname }}"
  