---
- name: Prepare Nodes for cluster
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: prereq

- name: Configure k3s Master Node
  hosts: master
  gather_facts: true
  become: true
  roles:
    - role: master

- name: Configure k3s Workers Node
  hosts: node
  gather_facts: true
  become: true
  roles:
    - role: workers
