---
# k3s Workers Installation
- name: Delete k3s Workers if already present
  ansible.builtin.file:
    path: "{{ workers_k3s_install_path }}"
    state: absent

- name: Download k3s Workers install script
  ansible.builtin.get_url:
    url: "{{ workers_k3s_install_url }}"
    dest: "{{ workers_k3s_install_path }}"
    mode: 'u+x'

- name: Install k3s as Workers
  ansible.builtin.command: sh {{ workers_k3s_install_path }}
  args:
    creates: "{{ workers_k3s_executable_path }}"
  environment:
    K3S_URL: "{{ workers_k3s_master_url }}"
    K3S_TOKEN: "{{ k3_token }}"

- name: Verify k3s Workers installation
  ansible.builtin.command: kubectl version --client
  register: k3s_version
  changed_when: false

- name: Display k3s Workers version
  ansible.builtin.debug:
    msg: "Installed k3s version: {{ k3s_version.stdout }}"
